exp_name: "Standard_Transformer_AT_Rolling_Claus_Resampled_Interval5_train_last_2400_cutastest"

data:
  path: "./data/Claus_dynamic/"
  training_files:
    - "R5_Train_Part.csv" # The first 80% (12000 pts)
  
  # Variables & Data Config
  variables_num: 8 
  point: 12000 # Use full length of the split file
  test_data_split: 0.0 # No more internal splitting, we did it manually
  valid_data_split: 0.15 # 15% to ensure enough validation samples (approx 100+)
  
  test_data:
    filename: "R5_ID_Test_Part.csv" 
    point: 2400
    
  inference_files:
    - name: "ID_Testing_Held_Out"
      filename: "R5_ID_Test_Part.csv" # The physical last 20%
      point: 2400
    - name: "OOD_Testing_R5-1"
      filename: "Test_dataform_change_air2_R=5-1.csv"
      point: 2400
    - name: "OOD_Testing_R5-2"
      filename: "Test_dataform_change_air2_R=5-2.csv"
      point: 2400
    - name: "OOD_Testing_R5-3"
      filename: "Test_dataform_change_air2_R=5-3.xlsx"
      point: 2400
    - name: "OOD_Testing_R5-4"
      filename: "Test_dataform_change_air2_R=5-4.xlsx"
      point: 2400
    - name: "OOD_Testing_R5-5"
      filename: "Test_dataform_change_air2_R=5-5.xlsx"
      point: 2400
    - name: "OOD_Testing_R5-6"
      filename: "Test_dataform_change_air2_R=5-6.csv"
      point: 2400

window:
  train_window_mins: 90 
  sampling_interval_min: 5 
  prediction_length: 72 

model:
  name: "transformer" 
  embedding_dim: 16     # Reduced from 32 to prevent overfitting on scarce data (1680 samples)
  hidden_dim: 16        
  n_layers: 2           # Reduced from 3 to 2
  num_heads: 1 
  activation: 'gelu'    
  dropout: 0.0          # No regularization needed for noise-free simulation data

training:
  device: "cuda"
  batch_size: 1024       # Smaller batch for gradient noise
  epochs: 10000 
  learning_rate: 0.001
  patience: 100
  loss_weighting:
    weights: [1.0, 1.0, 1.0, 1.0] 
  inference_strategy: 'sliding_window'
