exp_name: "transformer_layerwise_71var_decoder_input_sp_PGIN_From_Scratch"

data:
  path: "./data/Claus_dynamic/"
  training_files:
    - "Test_dataform_change_air2_R=5.csv"
    - "Test_dataform_change_air2_R=5-1.csv"
    - "Test_dataform_change_air2_R=5-2.csv"
    - "Test_dataform_change_air2_R=5-6.csv"
  
  variables_num: 68
  
  test_data_split: 0.1
  valid_data_split: 0.1
  
  inference_files: 
    - name: "R5_train_split"
      filename: "Test_dataform_change_air2_R=5_train_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-1_train_split"
      filename: "Test_dataform_change_air2_R=5-1_train_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-2_train_split"
      filename: "Test_dataform_change_air2_R=5-2_train_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-6_train_split"
      filename: "Test_dataform_change_air2_R=5-6_train_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5_test_split"
      filename: "Test_dataform_change_air2_R=5_test_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-1_test_split"
      filename: "Test_dataform_change_air2_R=5-1_test_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-2_test_split"
      filename: "Test_dataform_change_air2_R=5-2_test_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-6_test_split"
      filename: "Test_dataform_change_air2_R=5-6_test_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5_valid_split"
      filename: "Test_dataform_change_air2_R=5_valid_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-1_valid_split"
      filename: "Test_dataform_change_air2_R=5-1_valid_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-2_valid_split"
      filename: "Test_dataform_change_air2_R=5-2_valid_split.csv"
      inference_strategy: 'sliding_window'
    - name: "R5-6_valid_split"
      filename: "Test_dataform_change_air2_R=5-6_valid_split.csv"
      inference_strategy: 'sliding_window'


window:
  train_window_mins: 180    # 18 steps * 10 min
  sampling_interval_min: 10 
  use_median_downsampling: true 
  prediction_length: 18       # 18 steps

model:
  name: "transformer_layerwise"
  embedding_dim: 64     # Adjusted for ~60 variables (57 + pos) -> closest power of 2 or multiple of heads
  hidden_dim: 64       
  n_layers: 2
  num_heads: 1          # 64 is divisible by 1 (and 2, 4)
  activation: 'gelu' 
  dropout: 0.1
  ffn_expansion: 4      

training:
  device: "cuda"
  batch_size: 64
  epochs: 1000
  steps_per_epoch: 10
  learning_rate: 0.0005
  ss_loss_weight: 0
  smooth_loss_weight: 0.1
  gain_loss_weight: 1
  monitor_gain_kci: true
  dynamic_gain_method: "finite_difference"
  dynamic_gain_tail_start_step: 10
  finite_diff_delta_std: 0.5
  patience: 10
  loss_function: 'mse'
  loss_weighting:
    weights: [1.0, 1.0, 1.0, 1.0]
  
