exp_name: "Transformer_PlantData_17var"

data:
  path: "./data/Claus_dynamic/Claus_plant_data/"
  training_files:
    - "W251_500area_processed_Training_Data_part1.csv"
    - "W251_500area_processed_Training_Data_part2.csv"
    - "W251_500area_processed_Training_Data_part3.csv"
    - "W251_500area_processed_Training_Data_part4.csv"
    - "W251_500area_processed_Training_Data_part5.csv"
    - "W251_500area_processed_Training_Data_part6.csv"
    - "W251_500area_processed_Training_Data_part7.csv"
    - "W251_500area_processed_Training_Data_part8.csv"
  
  # Variables & Data Config
  variables_num: 17
  
  test_data_split: 0.0 # Using separate file so set split to 0
  valid_data_split: 0.1
  
  # Optional: inference files for post-training checks
  inference_files: 
    - name: "Training_Data_part1"
      filename: "W251_500area_processed_Training_Data_part1.csv"
      inference_strategy: 'sliding_window'
    - name: "Training_Data_part2"
      filename: "W251_500area_processed_Training_Data_part2.csv"
      inference_strategy: 'sliding_window'
    - name: "Training_Data_part"
      filename: "W251_500area_processed_Training_Data.csv"
      inference_strategy: 'sliding_window'
      point: 5000
    - name: "Test_PlantData"
      filename: "W251_500area_processed_Test_Data.csv"
      inference_strategy: 'sliding_window'

window:
  train_window_mins: 180    # 18 steps * 10 min (3 hours context)
  sampling_interval_min: 10 
  use_median_downsampling: true 
  prediction_length: 18       # 18 steps * 10 min (3 hours prediction)

model:
  name: "transformer"
  embedding_dim: 22     # Slightly increased for more variables
  hidden_dim: 22
  n_layers: 2           # Increased depth for complex real data
  num_heads: 2
  activation: 'relu'
  dropout: 0.1
  ffn_expansion: 2

training:
  device: "cuda"
  batch_size: 128
  epochs: 300
  learning_rate: 0.0005
  patience: 20
  loss_function: 'mse'
  loss_weighting:
    weights: [1.0, 1.0, 1.0, 1.0] 
  inference_strategy: 'block_replacement'
